"""
                    ~~ Trabajo Práctico 1 ~~
"""

"""
1.
Crea una función que reciba una lista de números y la ordene de menor a mayor. 
La función debe devolver la lista ordenada (Debe usar set).
"""
def Organizier_using_sets(numbers : list) -> list:
    """
    This function takes a list of numbers and organices them in ascending order.
    (Won't give a list with repeated numbers)  

    :Parameters: 
    numbers (list[int, float]) : A list containing numbers

    :Returns:
    List with unique numbers in ascending order
    """
    temporary_set = set()
    for number in numbers:
        temporary_set.add(number)
    return list(temporary_set)


"""
2.
Crea un programa que permita crear un conjunto desde cero y
después me permita eliminar un elemento de un conjunto si está presente en el conjunto.
"""
def Set_creator_user_and_random():
    """
    This function allows the user to create a set from scratch by adding integers.
    Then, it generates a random set of 40 unique integers between 1 and 100.
    :Returns:
    main_set(set) : the set generated by the user
    random_set(set): a random set
    """
    import random
    print("Creemos un conjunto desde cero.")
    main_set = set()
    get_out = True
    while get_out:
        user_input = input(f"Ingrese el número que desea agregar al conjunto ('q' para salir): \n")
        try:
            main_set.add(int(user_input))
        except:
            if user_input == "q":
                get_out = False
            else:
                print("Por favor ingrese únicamente números enteros o 'q' para salir.")

    print(f"El conjunto creado es: {main_set}")
    random_set = set(random.sample(range(1, 100), 40))
    print(f"El conjunto aleatorio generado es: {random_set}")
    return main_set, random_set

# main_set, random_set = Set_creator_user_and_random()

# repeated_elements = []
# for element in random_set:
#     if element in main_set:
#         repeated_elements.append(element)
# print(f"Los elementos que se encuentran en ambos conjuntos son: {repeated_elements}")


# get_out = True
# while get_out:
#     user_input = input(f"Ingrese el número que desea eliminar del conjunto('q' para salir): \n")
#     try:
#         main_set.remove(int(user_input))
#         print(f"El conjunto actualizado es: {main_set}")
#     except KeyError:
#         print("El elemento no se encuentra en el conjunto.")
#     except:
#         if user_input == "q":
#             get_out = False
#         else:
#             print("Por favor ingrese únicamente números enteros o 'q' para salir.")

# print("El conjunto final es:", main_set)

"""
3.
Dados dos conjuntos de números, 
escribe un programa para encontrar los números que faltan en el segundo 
conjunto en comparación con el primero y viceversa.
"""
# # main_set, random_set = Set_creator_user_and_random()
# missing_in_random = []
# missing_in_main = []
# for element in main_set:
#     if element not in random_set:
#         missing_in_random.append(element)

# for element in random_set:
#     if element not in main_set:
#         missing_in_main.append(element)

# print (f"Los elementos que están en el primer conjunto pero no en el segundo son: {missing_in_random}")
# print (f"Los elementos que están en el segundo conjunto pero no en el primero son: {missing_in_main}")

"""
4.
Escriba un programa en Python para eliminar todos los duplicados
de una lista de cadenas dada y devolver una lista de cadenas únicas.

"""

def List_of_data_user(initial_list:list) -> list:
    """
    This function takes a list with strings, duplicate or not and returns a list with 
    unique strings
    
    :Parameters:
    initial_list (list[any]): A list containing any type of data
    
    :Return:
    unique_set_list (list[any]) : Final list containing non duplicate data
    
    """
    final_list = set(initial_list)
    return list(final_list)                                 #   why does 'list(set(inital_list))' not work?



# main_set,random_set = Set_creator_user_and_random()

# repeated_list = list(main_set) + list(random_set) 
# print(repeated_list)
# print(List_of_data_user(repeated_list)) #Okay it's messy but it works

"""
5.
Crea una función llamada
factorial
que reciba un número entero positivo y devuelva su factorial. Ejemplo:
factorial(4)
debe devolver 24
"""

def Factorial(number:int,final_answer=1) -> int:
    """
    Function that returns the factorial of a number given at the start
    :Parameters:
    number (int) : the number given to the function
    :returns:
    final_answer (int) = the result of the mathemathical algorithm
    """
    final_answer *= number
    if (number-1) == 0:
        return final_answer
    return Factorial((number-1),final_answer)

# print(Factorial(10))


"""
6.
Crea una función llamada
fibonacci(n)
que reciba como parámetro un número entero n y devuelva una lista con los primeros n números de la serie de Fibonacci. 
La serie de Fibonacci es una secuencia en la que cada número se obtiene sumando los dos anteriores.
"""

def Fibonacci(number:int) -> list:
    """
    This function takes an integral number(n) a gives back the fibonacci sequence 'n' times

    :Parameters: 
    number(int): the amount of numbers of the fibonacci sequence

    :Return:
    fibo_list(list[int]): the fibonacci sequence up until 'n' numbers
    """
    fibo_list = []
    for i in range(number):
        fibo_number = i + (i+1)
        fibo_list.append(fibo_number)

    return fibo_list

# print(Fibonacci(4))

"""
7.
Crea una función recursiva llamada
suma_recursiva
que reciba un número
n
y devuelva la suma de los primeros
n
números naturales. Ejemplo:
suma_recursiva(5)
debe devolver 15 (1+2+3+4+5).
"""
def Suma_recursiva(n:int,result=0) -> int:
    """
    This function takes an integrer and sums it up with all its previous numbers until 0    
    
    :Parameters:
    n(int) : the number in question

    :Results:
    result(int) : the result of the mathemathical algorithm
    """
    result += n
    if (n-1) == 0:
        return result
    return Suma_recursiva(n-1,result)

# print(Suma_recursiva(8))


"""
8.
Crea una clase Libro con los atributos titulo, autor y año_publicacion. 
Luego, crea una subclase llamada LibroDigital que tenga un atributo adicional.
"""

class Libro:
    def __init__(self,titulo,autor,año_publicacion) -> None:
        self.titulo = titulo
        self.autor = autor
        self.año_publicación = año_publicacion
        pass


class LibroDigital(Libro):
    def __init__(self, titulo, autor, año_publicacion,peso_pdf) -> None:
        super().__init__(titulo, autor, año_publicacion)
        self.peso_pdf = peso_pdf
        pass



"""
9.
Dado un texto con información estructurada, escribí un programa que
extraiga los datos usando
slicing
y los devuelva como un diccionario.
A partir de un texto como el siguiente, la funcion deberia retornar el siguiente diccionario:
text = "Nombre: Juan Pérez | Edad: 30 | Ciudad: Salta"
slicing_function(text) # {"nombre": "Juan Perez", "edad" : 30, "ciudad": "Salta"}
"""

text = "Nombre: Juan Pérez | Edad: 30 | Ciudad: Salta"

list_text = text.split("|")
# print(list_text)
# list_text = text[0::"|"]
# print(list_text)

def Slicing_categories(category):
    """
    This function takes a set category of data and separates it between name and data

    :Parameters:
    category (str) : The set category of the function to separate

    :Returns:
    category_name (str) : The name of the category
    category_data (str) : The data corresponding to set category
    """
    category_name = ""
    category_data = ""
    validator = True
    for letter2 in category:
        if letter2 == ":":
            validator = False
        elif validator:
            category_name += letter2
        else:
            category_data += letter2
    return category_name,category_data


def Text_to_dict(text):
    """
    This funtion takes a text with a determinate order str('category:data' | 'category:data' | ...) and transforms it
    to a dictionary  dict({'category':data,'category':data,...})

    Parameters:
    text (str) : the text with the set order

    Returns:
    final_dict (dict) : The final dictionary that is going to be used for whatever pourpose
    """
    category = ""
    final_dict = {}
    for letter in text:
        if letter == "|":
            category_name,category_data = Slicing_categories(category)
            final_dict[category_name] = category_data
            category = ""
            letter=""
        category += letter
    category_name,category_data = Slicing_categories(category)
    final_dict[category_name] = category_data
    return final_dict


# print(Text_to_dict(text))



